import type { NewsAPICategory, NYTimesDesk } from '@/types/news';

export const NEWSAPI_CATEGORIES: { value: NewsAPICategory; label: string }[] = [
  { value: 'business', label: 'Business' },
  { value: 'entertainment', label: 'Entertainment' },
  { value: 'general', label: 'General' },
  { value: 'health', label: 'Health' },
  { value: 'science', label: 'Science' },
  { value: 'sports', label: 'Sports' },
  { value: 'technology', label: 'Technology' },
];

export const NYTIMES_DESKS: { value: NYTimesDesk; label: string }[] = [
  { value: 'Arts&Leisure', label: 'Arts & Leisure' },
  { value: 'BookReview', label: 'Book Review' },
  { value: 'Business', label: 'Business' },
  { value: 'Climate', label: 'Climate' },
  { value: 'Corrections', label: 'Corrections' },
  { value: 'Culture', label: 'Culture' },
  { value: 'Dining', label: 'Dining' },
  { value: 'Español', label: 'Español' },
  { value: 'Express', label: 'Express' },
  { value: 'Foreign', label: 'Foreign' },
  { value: 'Games', label: 'Games' },
  { value: 'Graphics', label: 'Graphics' },
  { value: 'Learning', label: 'Learning' },
  { value: 'Letters', label: 'Letters' },
  { value: 'Magazine', label: 'Magazine' },
  { value: 'Metro', label: 'Metro' },
  { value: 'NYTNow', label: 'NYT Now' },
  { value: 'National', label: 'National' },
  { value: 'Obits', label: 'Obits' },
  { value: 'OpEd', label: 'Op-Ed' },
  { value: 'Podcasts', label: 'Podcasts' },
  { value: 'Politics', label: 'Politics' },
  { value: 'RealEstate', label: 'Real Estate' },
  { value: 'Science', label: 'Science' },
  { value: 'Styles', label: 'Styles' },
  { value: 'Summary', label: 'Summary' },
  { value: 'SundayBusiness', label: 'Sunday Business' },
  { value: 'TStyle', label: 'T Style' },
  { value: 'Travel', label: 'Travel' },
  { value: 'Washington', label: 'Washington' },
  { value: 'Weather', label: 'Weather' },
  { value: 'Weekend', label: 'Weekend' },
  { value: 'Well', label: 'Well' },
];
